Add new board type MTB-UNIS
kmzbrnoI/mtb-daemon pull request #10
Opened 2023-04-17 22:29 UTC by petrilakm

2023-04-19 15:32 UTC, horacekj requested changes
Zatím jsem PR jen velice zběžně prolétl. Prosím zatím hlavně o stylistické úpravy, abych se mohl na kód vůbec pořádně dívat. Zejména o použití mezer/tabů v souladu s tím, jak jsou použity ve zbytku projektu. V tomto projektu se používají v C++ souborech pro vyjádření odsazení tabulátory.

2023-04-19 15:32 UTC, horacekj commented on src/main.cpp
> +				if (modules[addr] == nullptr) {
Tady je nějaké podivné odsazení.

2023-04-19 15:32 UTC, horacekj commented on src/modules/module.cpp
> +                        )
Má tady smysl natahovat volání funkce na tolik řádků? Já bych to klidně trochu zkomprimoval.

2023-04-19 15:32 UTC, horacekj commented on src/modules/unis.cpp
> +#include <QJsonArray>
Mezery vs. taby v celém souboru

2023-04-19 19:08 UTC, petrilakm commented on utils/manage.py
> +      print(uni_outputs_str(outputs))
proč jsou zde najednou mezery a ještě k tomu 4 (no fujú, když zbytek kodu má taby?

2023-04-19 19:14 UTC, petrilakm commented on utils/manage.py
> +      print(uni_outputs_str(outputs))
a flake8 nehodlám komentovat. vyžaduje úplné nesmysly. Ale co už opravím to jak chceš.

2023-04-20 20:29 UTC, horacekj commented on utils/manage.py
> +      print(uni_outputs_str(outputs))
> proč jsou zde najednou mezery a ještě k tomu 4 (no fujú, když zbytek kodu má taby?

Protože PEP8 předepisuje, že pythoní kód má striktně používat 4 mezery.

2023-04-20 21:27 UTC, horacekj requested changes
Prošel jsem PR detailněji. Koncepčně mi přijde PR v pohodě, implementace rámcově taky v pohodě. Navrhl jsem několik dílčích úprav.

2023-04-20 21:27 UTC, horacekj commented on src/modules/unis.cpp
> +			if (i < (16+8))
Zvážit, jestli místo `16` nepoužít `UNIS_IO_CNT`.

2023-04-20 21:27 UTC, horacekj commented on src/modules/module.cpp
> +	newaddr = request["new_address"].toInt(1);
Neměla by se spíš nechat výchozí hodnota argumentu 0 a když je nakonec `newaddr == 0`, tak vůbec nezavolat `mtbusb.send`, ale rovnou vrátit chybu?

2023-04-20 21:27 UTC, horacekj commented on src/modules/unis.cpp
> +			this->servoPosition[i] = jsonServoPosition[i].toInt(8000);
Tuhle konstantu vidím v kódu použitou už po několikáté. Vyčlenit do pojmenované konstanty?

2023-04-20 21:27 UTC, horacekj commented on src/modules/unis.cpp
> +			this->servoSpeed[i] = jsonServoSpeed[i].toInt(20);
Tuhle konstantu vidím v kódu použitou už po několikáté. Vyčlenit do pojmenované konstanty?

2023-04-20 21:27 UTC, horacekj commented on utils/manage.py
> +  manage.py [options] setaddress <new_address>
Unifikovat s ostatními příkazy: buď všechny mají používat `_` pro oddělení slov nebo žádný nemá používat `_` pro oddělení slov.

2023-04-20 21:27 UTC, horacekj commented on src/modules/unis.h
> +#ifndef MODULE_MTB_UNIS_H
Tady se pořád používají mezery pro odsazení.

2023-04-20 21:27 UTC, horacekj commented on src/modules/unis.cpp
> +  this->mlog("constructor of module UNIS (addr "+QString::number(addr)+")", Mtb::LogLevel::Debug);
zapomenutý log?

2023-04-20 21:27 UTC, horacekj commented on src/modules/unis.cpp
> +		if (port > UNIS_OUT_CNT)
Pozor, tady je asi off-by-one. Podmínka asi má být `if (port >= UNIS_OUT_CNT)`

2023-06-30 06:29 UTC, closed without merging